### ISSUE TITLE
Wrong translation in German language

### ISSUE THREAD

**Issue by STPKITT** [astro/ejabberd#1]
At the moment in the German language file there is an error in the translation and I can understand why it was made. It's in the line

{"Default users as participants", "Standardbenutzer als Teilnehmer"}.

The correct line should be:
{"Default users as participants", "Benutzer werden standardmäßig vollwertige Teilnehmer"}.

or
{"Default users as participants", "Benutzer werden standardmäßig Teilnehmer"}.

If the word "vollwertige" is the right word or if it should even be there at all is for others who are more into the matter to decide.

**Comment by astro** [comment]
This is a fork.

**Comment by STPKITT** [comment]
A fork of what?

**Comment by astro** [comment]
https://github.com/processone/ejabberd
